version: '3'
services:
  webserver:
    build: 
      context: ./nginx
      dockerfile: DockerFile
    ports: 
      - "80:80"    
    container_name: reverseproxy
    hostname: reverseproxy
    environment:
      - NGINX_PORT=80
  apinode:
    build:
      context: ./Nodejs
      dockerfile: DockerFile
    container_name: nodeapi
    hostname: nodeapi
    environment:
      - NODE_ENV=development
      - API_PORT=3000
      
  postgres:
    image: postgres
    restart: on-failure
    environment:
        POSTGRES_PASSWORD: root

  redis:
    image: redis
    restart: on-failure
